-- MySQL Script generated by MySQL Workbench
-- Thu Feb  6 22:51:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `id` VARCHAR(15) NOT NULL,
  `nick_name` VARCHAR(45) NULL,
  `date_add` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `birth_date` DATETIME NULL,
  `notes` MEDIUMTEXT NULL,
  `log` MEDIUMTEXT NULL,
  `league_country` VARCHAR(45) NULL,
  `league_city` VARCHAR(45) NULL,
  `league_district` VARCHAR(45) NULL,
  `league_other` VARCHAR(45) NULL COMMENT 'By subscribing to different leagues, the player can see his ranking among the other players from his school for example',
  `rfid_tag_uid` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATETIME NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`game_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATETIME NULL,
  `room_type` VARCHAR(45) NULL,
  `game_rule` VARCHAR(45) NULL,
  `game_level` INT NULL,
  `duration_s_theory` INT NULL,
  `duration_s_actual` INT NULL,
  `game_log` MEDIUMTEXT NULL COMMENT 'Contains all available info of what happened during the game_session (as opposed to normal log which is more dev related)',
  `log` MEDIUMTEXT NULL,
  `is_collaborative` TINYINT NULL COMMENT 'Defines if the players played collaboratively or in competition with eachother.',
  `parent_gs_id` VARCHAR(45) NULL COMMENT 'Here is to record the fact that this gs is part of a winning streak. if the current gs was started after the previous gs without changing or exiting the room, write its id here',
  `facility_id` INT NOT NULL,
  PRIMARY KEY (`id`, `facility_id`),
  INDEX `fk_game_session_facility1_idx` (`facility_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_session_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `mydb`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team` (
  `id` VARCHAR(15) NOT NULL COMMENT 'Special id construction : it must be a csv of the players ids sorted ASC',
  `name` VARCHAR(45) NULL,
  `nbr_of_players` INT NULL,
  `date_add` DATETIME NULL,
  `unique_identifier` VARCHAR(100) NULL COMMENT 'Contains a csv of the players ids sorted ASC',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`team_game_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team_game_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_add` DATETIME NULL,
  `score` INT NULL,
  `is_won` TINYINT NULL,
  `game_session_id` INT NOT NULL,
  `team_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `game_session_id`, `team_id`),
  INDEX `fk_player_result_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  INDEX `fk_player_result_team1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_result_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `mydb`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_result_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`facility_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facility_session` (
  `id` VARCHAR(15) NOT NULL,
  `date_add` DATETIME NULL,
  `date_exec` DATETIME NULL COMMENT 'When there may be a crucial difference between the date_add (time @ row insert) and the tine we actually want to confider the start of an event, we call it date_exec ( also called actual date). ',
  `duration_m` INT NULL,
  `facility_id` INT NOT NULL,
  `player_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `facility_id`, `player_id`),
  INDEX `fk_facility_session_facility3_idx` (`facility_id` ASC) VISIBLE,
  INDEX `fk_facility_session_player2_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_facility_session_facility3`
    FOREIGN KEY (`facility_id`)
    REFERENCES `mydb`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facility_session_player2`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`team_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team_player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` VARCHAR(15) NOT NULL,
  `player_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `team_id`, `player_id`),
  INDEX `fk_team_player_team1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_team_player_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_team_player_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_player_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`player_game_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player_game_session` (
  `id` INT NOT NULL,
  `date_add` DATETIME NULL,
  `score` INT NULL,
  `is_won` TINYINT NULL,
  `game_session_id` INT NOT NULL,
  `player_id` VARCHAR(15) NOT NULL,
  `team_id` VARCHAR(15) NOT NULL,
  `facility_session_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `game_session_id`, `player_id`, `team_id`, `facility_session_id`),
  INDEX `fk_player_game_session_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  INDEX `fk_player_game_session_player1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_player_game_session_team1_idx` (`team_id` ASC) VISIBLE,
  INDEX `fk_player_game_session_facility_session1_idx` (`facility_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_game_session_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `mydb`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_game_session_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_game_session_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_game_session_facility_session1`
    FOREIGN KEY (`facility_session_id`)
    REFERENCES `mydb`.`facility_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;